name: Laravel
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to prod
      uses: appleboy/ssh-action@master
      with:
          username: "chemflixglobal"
          host: "ssh041.webhosting.be"
          password: "Secure@123"
          script: 'cd /data/sites/web/chemflixglobal/subsites/smart-cities.databroker.global && ./auto_deploy.sh' #cd /var/www/html/MerqataAPI && ./server_deploy.sh
